export const AndroidData = [
  { 
    "currency": "USD",
    "description": "Savings Zone Monthly Subscription",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$2.99",
    "priceValue": 2.99,
    "productId": "com.savings.zone.sub.monthly",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "P1M",
    "title": "Savings Zone Monthly Subscription (Savings Zone)",
  },
  { 
    "currency": "USD",
    "description": "Savings Zone Six Months Subscription",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$17.99",
    "priceValue": 17.99,
    "productId": "com.savings.zone.sub.sixmonths",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "P6M",
    "title": "Savings Zone Six Months Subscription (Savings Zone)",
  },
  { 
    "currency": "USD",
    "description": "Savings Zone Yearly Subscription",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$34.99",
    "priceValue": 34.99,
    "productId": "com.savings.zone.sub.year",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "P1Y",
    "title": "Savings Zone 1 Year Subscription (Savings Zone)",
  }
]
export const AndroidDataTest = [
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.canceled.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.canceled",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  },
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.item_unavailable.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.item_unavailable",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  },
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.purchased.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.purchased",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  },
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.refunded.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.refunded",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  }
]
export const iosData = [
  {
    "countryCode": "US",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "description": "Enjoy all coupons for 1 month",
    "downloadable": "false",
    "identifier": "com.savings.zone.sub.monthly",
    "price": 2.9899999999999998,
    "priceString": "$2.99",
    "title": "Savings Zone (1 Month)",
  },
  {
    "countryCode": "US",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "description": "Enjoy all coupons for 6 months",
    "downloadable": "false",
    "identifier": "com.savings.zone.sub.sixmonths",
    "price": 17.990000000000002,
    "priceString": "$17.99",
    "title": "Savings Zone (6 Months)",
  },
  {
    "countryCode": "US",
    "currencyCode": "USD",
    "currencySymbol": "$",
    "description": "Enjoy all coupons for 1 year",
    "downloadable": "false",
    "identifier": "com.savings.zone.sub.year",
    "price": 34.989999999999995,
    "priceString": "$34.99",
    "title": "Savings Zone (1 Year)",
  },
]

export const gpbErrors = {
  'PAYMENT_OK':'Suecess',
  'PAYMENT_CANCELLED':'Purchase or subscribe failed with error: 1',
  'PAYMENT_DECLINED':'Purchase or subscribe failed with error: 6',
  'PAYMENT_BUG':'Purchase or subscribe failed with error: 102',
  'ITEM_UNAVAILABLE':'Purchase or subscribe failed with error: 4'
}




