export const AndroidData = [
  { 
    "currency": "USD",
    "description": "Savings Zone Monthly Subscription",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$2.99",
    "priceValue": 2.99,
    "productId": "com.savings.zone.sub.monthly",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "P1M",
    "title": "Savings Zone Monthly Subscription (Savings Zone)",
  },
  { 
    "currency": "USD",
    "description": "Savings Zone Six Months Subscription",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$17.99",
    "priceValue": 17.99,
    "productId": "com.savings.zone.sub.sixmonths",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "P6M",
    "title": "Savings Zone Six Months Subscription (Savings Zone)",
  },
  { 
    "currency": "USD",
    "description": "Savings Zone Yearly Subscription",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$34.99",
    "priceValue": 34.99,
    "productId": "com.savings.zone.sub.year",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "P1Y",
    "title": "Savings Zone 1 Year Subscription (Savings Zone)",
  }
]
export const AndroidDataTest = [
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.canceled.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.canceled",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  },
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.item_unavailable.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.item_unavailable",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  },
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.purchased.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.purchased",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  },
  {
    "currency": "USD",
    "description": "Sample description for product: android.test.refunded.",
    "haveIntroductoryPeriod": false,
    "haveTrialPeriod": false,
    "introductoryPriceCycles": 0,
    "introductoryPricePeriod": "",
    "introductoryPriceText": "",
    "introductoryPriceValue": 0,
    "isSubscription": true,
    "priceText": "$0.99",
    "priceValue": 0.99,
    "productId": "android.test.refunded",
    "subscriptionFreeTrialPeriod": "",
    "subscriptionPeriod": "",
    "title": "Sample Title",
  }
]
export const iosData = [
  {
    "currency": "USD",
    "description": "Obten ofertas por un periodo de 1 mes",
    "discounts": [],
    "introductoryPrice": "",
    "introductoryPriceNumberOfPeriodsIOS": "",
    "introductoryPricePaymentModeIOS": "",
    "introductoryPriceSubscriptionPeriodIOS": "",
    "localizedPrice": "$2.99",
    "price": "2.99",
    "productId": "savings.zone.sub.monthly",
    "subscriptionPeriodNumberIOS": "0",
    "subscriptionPeriodUnitIOS": "DAY",
    "title": "Savings Zone (1 mes)",
    "type": "Do not use this. It returned sub only before",
  },
  {
    "currency": "USD",
    "description": "Obten ofertas por un periodo de 6 meses",
    "discounts": [],
    "introductoryPrice": "",
    "introductoryPriceNumberOfPeriodsIOS": "",
    "introductoryPricePaymentModeIOS": "",
    "introductoryPriceSubscriptionPeriodIOS": "",
    "localizedPrice": "$16.99",
    "price": "16.99",
    "productId": "savings.zone.sub.sixmonths",
    "subscriptionPeriodNumberIOS": "0",
    "subscriptionPeriodUnitIOS": "DAY",
    "title": "Savings Zone (6 Meses)",
    "type": "Do not use this. It returned sub only before",
  },
  {
    "currency": "USD",
    "description": "Obten ofertas por un periodo de 1 año",
    "discounts": [],
    "introductoryPrice": "",
    "introductoryPriceNumberOfPeriodsIOS": "",
    "introductoryPricePaymentModeIOS": "",
    "introductoryPriceSubscriptionPeriodIOS": "",
    "localizedPrice": "$34.99",
    "price": "34.99",
    "productId": "savings.zone.sub.year",
    "subscriptionPeriodNumberIOS": "0",
    "subscriptionPeriodUnitIOS": "DAY",
    "title": "Savings Zone (1 año)",
    "type": "Do not use this. It returned sub only before",
  },
]

export const gpbErrors = {
  'PAYMENT_OK':'Suecess',
  'PAYMENT_CANCELLED':'Purchase or subscribe failed with error: 1',
  'PAYMENT_DECLINED':'Purchase or subscribe failed with error: 6',
  'PAYMENT_BUG':'Purchase or subscribe failed with error: 102',
  'ITEM_UNAVAILABLE':'Purchase or subscribe failed with error: 4'
}




